name: Release
run-name: Release ${{ github.ref_name }}

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.18.0"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build plugin
              run: npm run build

            - name: Get version from tag
              id: version
              run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

            - name: Create release
              run: |
                  gh release create ${{ github.ref_name }} \
                    --title "obsidian-stomp-${{ github.ref_name }}" \
                    --generate-notes --draft \
                    ./main.js ./manifest.json ./styles.css
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
